package entity;
// Generated 10 Jul 2017 10:59:28 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Card generated by hbm2java
 */
@Entity
@Table(name="card"
    ,catalog="absa"
)
public class Card  implements java.io.Serializable {


     private Integer id;
     private String fullname;
     private String surname;
     private String nationality;
     private String countryofbirth;
     private String countryofresidence;
     private String homelanguage;
     private String maritalstatus;
     private int cellphonenumber;
     private String email;
     private String empaddress;
     private String employementstatus;
     private String jobTitle;
     private String industry;
     private String grossmontlhyincome;
     private String sourceofincome;
     private String totalmontlhyexpences;

    public Card() {
    }

    public Card(String fullname, String surname, String nationality, String countryofbirth, String countryofresidence, String homelanguage, String maritalstatus, int cellphonenumber, String email, String empaddress, String employementstatus, String jobTitle, String industry, String grossmontlhyincome, String sourceofincome, String totalmontlhyexpences) {
       this.fullname = fullname;
       this.surname = surname;
       this.nationality = nationality;
       this.countryofbirth = countryofbirth;
       this.countryofresidence = countryofresidence;
       this.homelanguage = homelanguage;
       this.maritalstatus = maritalstatus;
       this.cellphonenumber = cellphonenumber;
       this.email = email;
       this.empaddress = empaddress;
       this.employementstatus = employementstatus;
       this.jobTitle = jobTitle;
       this.industry = industry;
       this.grossmontlhyincome = grossmontlhyincome;
       this.sourceofincome = sourceofincome;
       this.totalmontlhyexpences = totalmontlhyexpences;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="fullname", nullable=false, length=45)
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    
    @Column(name="surname", nullable=false, length=45)
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }

    
    @Column(name="nationality", nullable=false, length=45)
    public String getNationality() {
        return this.nationality;
    }
    
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    
    @Column(name="countryofbirth", nullable=false, length=45)
    public String getCountryofbirth() {
        return this.countryofbirth;
    }
    
    public void setCountryofbirth(String countryofbirth) {
        this.countryofbirth = countryofbirth;
    }

    
    @Column(name="countryofresidence", nullable=false, length=45)
    public String getCountryofresidence() {
        return this.countryofresidence;
    }
    
    public void setCountryofresidence(String countryofresidence) {
        this.countryofresidence = countryofresidence;
    }

    
    @Column(name="homelanguage", nullable=false, length=45)
    public String getHomelanguage() {
        return this.homelanguage;
    }
    
    public void setHomelanguage(String homelanguage) {
        this.homelanguage = homelanguage;
    }

    
    @Column(name="maritalstatus", nullable=false, length=45)
    public String getMaritalstatus() {
        return this.maritalstatus;
    }
    
    public void setMaritalstatus(String maritalstatus) {
        this.maritalstatus = maritalstatus;
    }

    
    @Column(name="cellphonenumber", nullable=false)
    public int getCellphonenumber() {
        return this.cellphonenumber;
    }
    
    public void setCellphonenumber(int cellphonenumber) {
        this.cellphonenumber = cellphonenumber;
    }

    
    @Column(name="email", nullable=false, length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="empaddress", nullable=false, length=45)
    public String getEmpaddress() {
        return this.empaddress;
    }
    
    public void setEmpaddress(String empaddress) {
        this.empaddress = empaddress;
    }

    
    @Column(name="employementstatus", nullable=false, length=45)
    public String getEmployementstatus() {
        return this.employementstatus;
    }
    
    public void setEmployementstatus(String employementstatus) {
        this.employementstatus = employementstatus;
    }

    
    @Column(name="job_title", nullable=false, length=45)
    public String getJobTitle() {
        return this.jobTitle;
    }
    
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }

    
    @Column(name="industry", nullable=false, length=45)
    public String getIndustry() {
        return this.industry;
    }
    
    public void setIndustry(String industry) {
        this.industry = industry;
    }

    
    @Column(name="grossmontlhyincome", nullable=false, length=45)
    public String getGrossmontlhyincome() {
        return this.grossmontlhyincome;
    }
    
    public void setGrossmontlhyincome(String grossmontlhyincome) {
        this.grossmontlhyincome = grossmontlhyincome;
    }

    
    @Column(name="sourceofincome", nullable=false, length=45)
    public String getSourceofincome() {
        return this.sourceofincome;
    }
    
    public void setSourceofincome(String sourceofincome) {
        this.sourceofincome = sourceofincome;
    }

    
    @Column(name="totalmontlhyexpences", nullable=false, length=45)
    public String getTotalmontlhyexpences() {
        return this.totalmontlhyexpences;
    }
    
    public void setTotalmontlhyexpences(String totalmontlhyexpences) {
        this.totalmontlhyexpences = totalmontlhyexpences;
    }




}


